window.mo = {}
mo._allowCopy = []
require('./m/linkage/index.js')
mo._allowCopy.push('linkage')
require('./m/2/index.js')
require('./m/box/index.js')
require('./m/ajax/index.js')
require('./m/form-input/index.js')
require('./m/copy/index.js')
require('./m/upload/index.js')
mo._allowCopy.push('upload')
require('./m/login/index.js')
require('./m/alert/index.js')
require('./m/remove/index.js')
require('./m/sort/index.js')
